mode: dev
data:
  dev_paths: ['data/libri_test/data_list_sorted.json']
  text:
    mode: character
    vocab: data/libri_train_1h/vocab_char.txt
  max_len: 1000000

decode:
  type: greedy  # beam / greedy
  token: language_model/token.txt
  lm: language_model/3-gram.pruned.3e-7.bin
  lexicon: language_model/librispeech-char-lexicon.txt
  beam_max_score: 100000.0 
  beam_size: 50
  token_beam_size: 20
  beam_threshold: 1000
  lm_weight: 2.0
  word_score: -0.5
  sil_score: 0.0
  log_add: False


hparam:
  val_batch_size: 16
  njobs: 4
  pin_memory: true

trainer:
  gpus: 1
  logger: false
  default_root_dir: model/ctc_libri-10h_char
  deterministic: true
