mode: dev
data:
  dev_paths: ['data/libri_test/data_list_sorted.json']
  text:
    mode: character
    vocab: data/libri_train_1h/vocab_char.txt

decode:
  type: beam  # beam / greedy
  beam_max_score: 10000.0 
  beam_size: 50
  token_beam_size: 20
  beam_threshold: 1000
  lm_weight: 2.0
  word_score: -0.5
  sil_score: 0.0
  log_add: False


hparam:
  val_batch_size: 16
  njobs: 4
  pin_memory: true

trainer:
  gpus: 1
  logger: false
  default_root_dir: model/ctc_libri-10h_char
  deterministic: true
